#!/bin/bash


case $1 in

clone)
xrandr --output HDMI2 --mode 1920x1080 --same-as LVDS1 --mode 1920x1080
;;

right)
xrandr --output HDMI2 --mode 1920x1080 --right-of LVDS1 --mode 1920x1080

esac

# xrandr --auto --output HDMI2


