#!/bin/bash



TIME=$(date +"%yy%mm%dd%Hh%Mm%Ss")
FOLDER=$(echo ${PWD##*/})

if [ -d ".git" ]; then
        echo "Abort: Git directory detect."
        exit 0
fi

if [ "$1" == "" ]; then
        REPOS_NAME=$FOLDER-$TIME
else
        REPOS_NAME=$1
fi

curl -L -u 'maxiwell' https://api.github.com/user/repos -d '{"name":"'$REPOS_NAME'"}' > /dev/null
git init
git add *
git commit -m "Initial commit"
git remote add origin git@github.com:maxiwell/$REPOS_NAME 
git push -u origin master



