#!/bin/bash


TIME=$(date +"%yy%mm%dd%Hh%Mm%Ss")
FOLDER=$(echo ${PWD##*/})
PATHFOLDER=$PWD


if [ -d ".git" ]; then
        echo "Abort: Git directory detect."
        exit 0
fi

if [ "$1" == "-h" ]; then
    echo "usage: gitcreate  [-s server]  [repository_name]"
    exit 0
fi

if [ "$1" == "-s" ]; then
    SERVER="$2:/home/max/git"
else
    SERVER="git@github.com:maxiwell"
fi

echo "Server: $SERVER"


if [ "$1" == "-s" ]; then
    if  [ "$3" == "" ]; then
        REPOS_NAME=$FOLDER-$TIME
    else
        REPOS_NAME=$3
    fi
else
    if [ "$1" == "" ]; then
        REPOS_NAME=$FOLDER-$TIME
    else
        REPOS_NAME=$1
    fi
fi

echo "Repository: $REPOS_NAME"


if echo "$SERVER" | grep github > /dev/null ; then
    if [ ! -f /usr/bin/curl ]; then
            echo "I require \"curl\" but it's not installed.  Aborting."
            exit 1;
    fi
    
    curl -sS -L -u 'maxiwell' https://api.github.com/user/repos -d '{"name":"'$REPOS_NAME'","description":"'$PATHFOLDER'"}'  > temp
    badcredentials=`cat temp | grep -c "Bad credentials"`
    rm temp
    if [ "$badcredentials" != 0 ]; then
            echo "GitHub: Bad credentials. Aborting"
            exit 1;
    fi
else
    ssh $2 "mkdir /home/max/git/$REPOS_NAME && cd /home/max/git/$REPOS_NAME && git --bare init"
fi

if [  `ls -1 | wc -l` -eq 0 ]; then
        touch README.md
fi

git init
git add *
git commit -m "Initial commit"
git remote add origin $SERVER/$REPOS_NAME 
git push -u origin master



