#!/bin/bash



if [ "$1" == "-c" ]; 
then # connect mode

    hdmi_on=`xrandr | grep -c "HDMI2 connected"`
    if [ $hdmi_on -eq 1 ]; then
        pactl set-card-profile 0 output:hdmi-stereo
    else
        pactl set-card-profile 0 output:analog-stereo+input:analog-stereo
    fi

else  # toggle mode

    mode=`pactl stat | grep -c hdmi-stereo`
    if [ $mode -eq 0 ]; then
         pactl set-card-profile 0 output:hdmi-stereo
    else   
         pactl set-card-profile 0 output:analog-stereo+input:analog-stereo
    fi

fi
