#!/bin/bash

# Script to mark a file or folder to sync with git
# Only works if that file is in the $HOME folder

# -c : check if files are synchronized

GITDIR=$HOME/.github/LinuxConfig

if [[ $1 == '' ]]; then
    echo "File or folder missing..."
else
    if [[ $1 == '-c' ]]; then
        echo -e "\nCheck mode: |*| Sync  | | Unsync\n"
        if [[ $2 == '' ]]; then
            echo "File of folder missing..."
        else
            shift # discards the $1 (-c) args
            for i; do 
               if [[ -e $GITDIR/$PWD/$i ]]; then # if file exists
                   echo "|*| $GITDIR/$PWD/$i"
               else
                   echo "| | $GITDIR/$PWD/$i"
               fi
            done
            echo ""
        fi
    else
        for i; do 
           cp -r --parents $PWD/$i $GITDIR
           echo "$GITDIR/$PWD/$i"
        done
    fi
fi





