- hosts: all
  tasks:
    - name: APT - homebank
      apt_repository:
        repo: ppa:mdoyen/homebank
    - name: APT - wine
      apt_repository:
        repo: ppa:ubuntu-wine/ppa
    - name: APT - php5
      apt_repository:
        repo: ppa:ondrej/php
    - name: APT - java
      apt_repository: 
        repo: ppa:webupd8team/java
    - name: APT - vim
      apt_repository:
        repo: ppa:jonathonf/vim
    - name: APT - Mozilla 
      apt_repository:
        repo: ppa:ubuntu-mozilla-security/ppa

    - name: APT - spotify
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: BBEBDCB318AD50EC6865090613B00F1FD2C19886
    - apt_repository:
        repo: 'deb http://repository.spotify.com stable non-free'
        state: present

    - name: APT - dropbox 
      apt_key:
        keyserver: pgp.mit.edu
        id: 5044912E
    - apt_repository:
        repo: 'deb http://linux.dropbox.com/ubuntu/ {{ansible_lsb.codename}} main'
        state: present

    - name: APT - virtualbox 
      apt_key:
        url: "http://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc"
        state: present
    - apt_repository:
        repo: 'deb http://download.virtualbox.org/virtualbox/debian {{ansible_lsb.codename}} contrib'
        state: present

    - name: APT - chrome
      apt_key:
        url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
        state: present
    - apt_repository:
        repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
        state: present

    - name: APT - docker 
      apt_key:
        keyserver: p80.pool.sks-keyservers.net
        id: 58118E89F3A912897C070ADBF76221572C52609D
    - apt_repository:
        repo: 'deb https://apt.dockerproject.org/repo ubuntu-{{ansible_lsb.codename}} main'
        state: present

    - name: APT - stack haskell 
      apt_key:
        url: "https://s3.amazonaws.com/download.fpcomplete.com/ubuntu/fpco.key"
        state: present
    - apt_repository:
        repo: 'deb http://download.fpcomplete.com/ubuntu/{{ansible_lsb.codename}} stable main'
        state: present

      #- name: Update repositories
      #- apt:
      #-     update_cache: yes

    - name: Dev tools
      apt: name={{item}} state=installed
      with_items:
          - gcc
          - g++
          - clang
          - clang-format
          - build-essential
          - cmake
          - ninja-build
          - flex
          - bison
          - ghc
          - stack
          - git
          - subversion
          - gcc-multilib
          - g++-multilib
          - dwarfdump
          - autoconf
          - help2man
          - rustc
          - cargo
          - uuid-dev
          - ccache

    - name: Libraries 
      apt: name={{item}} state=installed
      with_items:
          - libofx-dev
          - libncurses5
          - libncurses5-dev
          - libmono-system-xml-linq4.0-cil 
          - libmono-system-data-datasetextensions4.0-cil 
          - libmono-system-runtime-serialization4.0-cil 
          - mono-mcs
          - libdw-dev
          - libclang-dev
          - libssl-dev
          - zlibc
          - libglib2.0-dev
          - libgtk-3-dev
          - libnss3-tools
          - openssl


    - name: Uninstall packages 
      apt: name={{item}} state=absent
      with_items:
          - gnome-screensaver

    - name: Openbox packages
      apt: name={{item}} state=installed
      with_items:
          - openbox
          - rxvt-unicode-256color
          - terminator
          - tint2
          - gsimplecal
          - gmrun
          - conky-all
          - wmctrl
          - htop
          - iotop
          - pavucontrol
          - xscreensaver
          - xbacklight
          - xvfb
          - nemo
          - trash-cli
          - xclip
          - scrot
          - network-manager-openvpn
          - network-manager-openvpn-gnome
          - human-theme
          - ecryptfs-utils

    - name: Productivity Tools
      apt: name={{item}} state=installed
      with_items:
          - tmux
          - vim-gtk
          - tig
          - weechat
          - znc
          - git-svn
          - git-bzr
          - git-remote-bzr
          - tree
          - smartmontools
          - shc
          - exuberant-ctags
          - cscope
          - silversearcher-ag
          - jq

    - name: PHP
      apt: name={{item}} state=installed
      with_items:
          - php
          - php-curl
          - php-xml
          - php-mbstring
          - php7.0
          - php7.0-curl
          - php7.0-xml
          - php7.0-json
          - php7.0-mbstring

    - name: Network packages
      apt: name={{item}} state=installed
      with_items:
          - inadyn
          - ssh
          - lynx
          - elinks
          - apache2
          - mosh
          - nmap
          - cifs-utils

    - name: Apache2 - Add userdir module
      apache2_module:
          state: present
          name: userdir

    - name: Apache2 - Create public_html folder
      become: yes
      become_user: '{{local_user}}'
      file: path='{{local_home}}/public_html' mode=775 state=directory

    - name: Make GNOME's lock screen use xscreensaver
      file: 
          src: '/usr/bin/xscreensaver-command'
          dest: '/usr/bin/gnome-screensaver-command'
          state: link

    - name: Python packages
      apt: name={{item}} state=installed
      with_items:
          - python-pip 
          - python3-pip

    - name: Other
      apt: name={{item}} state=installed
      with_items:
          - google-chrome-stable
          - firefox
          - virtualbox
          - dropbox
          - homebank
          - keepass2
          - deluge
          - gparted
          - wine
          - docker
          - rdesktop
          - mplayer
          - mpv
          - vlc
          - unrar
          - spotify-client
          - gimp
          - stress
          - mtp-tools
          - mtd-tools
          - lzop
          - lzma

    - name: Latex packages
      apt: name={{item}} state=installed 
      with_items:
          - texlive-full

    - name: Vim Undo Folder
      become: yes
      become_user: '{{local_user}}'
      file: path='{{local_home}}/.vim/undo' mode=775 state=directory

    - name: RXVT Plugin Install
      become: yes
      become_user: '{{local_user}}'
      file: 
          src: '{{local_home}}/.local/opt/rxvt-tabbed-new/tabbed_new' 
          dest: '{{local_home}}/.urxvt/ext/tabbed_new'
          state: link

    - stat: path='{{local_home}}/.local/share/fonts/Ubuntu Mono derivative Powerline.ttf'
      register: p

    - name: Powerline Fonts Install
      become: yes
      become_user: '{{local_user}}'
      command: chdir={{local_home}}/.local/opt/powerline-fonts ./install.sh
      when: p.stat.islnk is not defined 

    - name: Accept Java 8 License
      become: yes
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
 
    - name: Install Oracle Java 8
      become: yes
      apt: name={{item}} state=latest
      with_items:
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default

    - name: Install Oracle Java 8 Firefox Plugin
      file:
          src: /usr/lib/jvm/java-8-oracle/jre/lib/amd64/libnpjp2.so
          dest: /usr/lib/firefox/browser/plugins/libnpjp2.so
          state: link

    - name: Install KeePassHTTP plugin
      get_url: 
          url: https://raw.github.com/pfn/keepasshttp/master/KeePassHttp.plgx
          dest: /usr/lib/keepass2/KeePassHttp.plgx
          mode: 0644

    - name: Pip2 Packages
      pip: name={{item}} state=present executable=pip2
      with_items:
          - grip
          - selenium
          - powerline-status
          - websocket-client

    - name: Pip3 Packages
      pip: name={{item}} state=present executable=pip3
      with_items:
          - grip
          - selenium
          - powerline-status
          - onedrivesdk
          - websocket-client

    - name: VIM - Install Plugins using Vundle
      become: yes
      become_user: '{{local_user}}'
      command: vim +BundleInstall +quitall
      register: res
      changed_when: "res.rc > 0"

    - stat: path='{{local_home}}/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so'
      register: ycm

    - name: VIM - Install YouCompleteMe plugin
      become: yes
      become_user: '{{local_user}}'
      command: chdir={{local_home}}/.vim/bundle/YouCompleteMe ./install.py --clang-completer
      when: ycm.stat.islnk is not defined

    - stat: path='/usr/bin/rclone'
      register: rclone

    - name: Download rclone 
      unarchive: 
          src: http://downloads.rclone.org/rclone-current-linux-amd64.zip
          dest: /tmp/
          remote_src: True
          copy: False
      when: rclone.stat.islnk is not defined

    - name: Install rclone 
      copy: src={{item}} dest='/usr/bin/rclone' mode=0755
      with_fileglob: /tmp/rclone*/rclone


    - name: Install gsync-backup
      become: yes
      become_user: '{{local_user}}'
      file: 
          src: '{{local_home}}/.local/opt/gsync-backup/gsync-backup.sh'
          dest: '{{local_home}}/.local/bin/gsync-backup.sh'
          state: link

    - name: Ensures that weechat dir exists
      become: yes
      become_user: '{{local_user}}'
      file: path={{item}} state=directory
      with_items:
          - '{{local_home}}/.weechat/perl/autoload'
          - '{{local_home}}/.weechat/python/autoload'


    - name: WeeChat - Install Buffers
      become: yes
      become_user: '{{local_user}}'
      get_url: 
          url:  https://weechat.org/files/scripts/buffers.pl
          dest: '{{local_home}}/.weechat/perl/autoload/buffers.pl'
          mode: 0644

    - name: WeeChat - Install Wee Slack
      become: yes
      become_user: '{{local_user}}'
      get_url: 
          url:  https://raw.githubusercontent.com/rawdigits/wee-slack/master/wee_slack.py
          dest: '{{local_home}}/.weechat/python/autoload/wee_slack.py'
          mode: 0644

    - name: WeeChat - Install iset
      become: yes
      become_user: '{{local_user}}'
      get_url:
          url: https://weechat.org/files/scripts/iset.pl
          dest: '{{local_home}}/.weechat/perl/autoload/iset.pl'
          mode: 0644

    - file:
        path: "{{item}}"
        state: absent
      with_fileglob:
          - /etc/init.d/*warsaw*
          - /etc/rc*/*warsaw*

    - name: Warsaw - Link to SystemD
      file:
          src: ~/.local/share/warsaw.service 
          dest: /etc/systemd/system/multi-user.target.wants/warsaw.service
          state: link

