- hosts: all
  tasks:
    - rpm_key:
        state: present
        key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    - command:
        cmd: dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
        warn: false
        creates: /etc/yum.repos.d/brave-browser-rpm-release.s3.brave.com_x86_64_.repo

    - name: Libs and Dev Tools
      package: name={{item}} state=installed
      with_items:
          - gcc
          - gcc-c++
          - clang
          - cmake
          - ninja-build
          - flex
          - bison
          - ghc
          - autoconf
          - automake
          - libtool
          - help2man
          - rustc
          - cargo
          - ccache
          - mpfr
          - mpfr-devel
          - gmp
          - gmp-devel
          - libmpc
          - libmpc-devel
          - gtk2-devel
          - ncurses-devel
          - bc
          - libguestfs-tools
          - lttng-ust
          - lttng-tools
          - babeltrace
          - libxml2-devel
          - libnl3-devel
          - gnutls-devel
          - rpcgen
          - device-mapper-devel
          - libtirpc-devel
          - libpciaccess-devel
          - readline-devel

    - name: PowerPC Packages
      package: name={{item}} state=installed
      with_items:
          - binutils-powerpc64-linux-gnu
          - gcc-powerpc64-linux-gnu
          - gcc-c++-powerpc64-linux-gnu

    - name: Openbox Packages
      package: name={{item}} state=installed
      with_items:
          - openbox
          - terminator
          - tint2
          - conky
          - wmctrl
          - htop
          - iotop
          - xscreensaver
          - xbacklight
          - trash-cli
          - xclip
          - scrot
          - notification-daemon
          - network-manager-applet
          - xrandr
          - flameshot

    - name: Productivity Tools
      package: name={{item}} state=installed
      with_items:
          - tmux
          - subversion
          - git
          - git-email
          - tig
          - weechat
          - hexchat
          - znc
          - tree
          - cscope
          - ctags
          - jq
          - gawk
          - hexchat
          - redhat-rpm-config
          - expect
          - unar
          - mutt
          - notmuch
          - offlineimap
          - mailcap
          - lynx
          - socat
          - python3
          - valgrind
          - ipmitool
          - xsetroot
          - docker

    - name: Personal Stuffs
      package: name={{item}} state=installed
      with_items:
          - mpv
          - homebank
          - keepassxc
          - inadyn
          - duplicity
          - samba
          - brave-browser
          - texlive-scheme-full
          - x2goclient
          - ecryptfs-utils

    - name: Python Packages
      package: name={{item}} state=installed
      with_items:
          - python3-devel
          - python3-xlrd

    - rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    - name: gmrun
      yum: name=https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/g/gmrun-0.9.2-29.el7.x86_64.rpm

    - rpm_key:
        state: present
        key: https://dl.teamviewer.com/download/linux/signature/TeamViewer2017.asc
    - name: Install TeamViewer
      yum:
        name: https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm

      #- name: IBM Packages
      #  package: name={{item}} state=installed
      #  with_items:
      #      - '@IBM Client Base'
      #      - '@IBM Licensed'
      #      - '@IBM Notes'
      #      - '@Development Tools'
      #      - '@C Development Tools and Libraries'
      #      - ibm-ca-certificates
      #      - CrashPlan
      #      - ecpinstall
      #      - ecpdelegate
      #      - ibm-dnf-plugins
