- hosts: all
  tasks:
    - name: Libs and Dev Tools
      package: name={{item}} state=installed
      with_items:
          - gcc
          - gcc-c++
          - clang
          - cmake
          - ninja-build
          - flex
          - bison
          - ghc
          - autoconf
          - automake
          - libtool
          - help2man
          - rustc
          - cargo
          - ccache
          - mpfr
          - mpfr-devel
          - gmp
          - gmp-devel
          - libmpc
          - libmpc-devel
          - gtk2-devel
          - ncurses-devel
          - bc
          - libguestfs-tools
          - lttng-ust
          - lttng-tools
          - babeltrace
          - python2-devel
          - python3-devel
          - libxml2-devel
          - libnl3-devel
          - gnutls-devel
          - rpcgen
          - device-mapper-devel
          - libtirpc-devel
          - libpciaccess-devel
          - readline-devel

    - name: PowerPC Packages
      package: name={{item}} state=installed
      with_items:
          - binutils-powerpc64-linux-gnu
          - gcc-powerpc64-linux-gnu
          - gcc-c++-powerpc64-linux-gnu

    - name: Openbox Packages
      package: name={{item}} state=installed
      with_items:
          - openbox
          - rxvt-unicode-256color
          - terminator
          - tint2
          - gmrun
          - conky
          - wmctrl
          - htop
          - iotop
          - pavucontrol
          - xscreensaver
          - xbacklight
          - trash-cli
          - xclip
          - scrot
          - notification-daemon
          - network-manager-applet

    - name: Productivity Tools
      package: name={{item}} state=installed
      with_items:
          - tmux
          - subversion
          - git
          - git-email
          - tig
          - weechat
          - hexchat
          - znc
          - tree
          - cscope
          - ctags
          - jq
          - gawk
          - hexchat
          - redhat-rpm-config
          - expect
          - unar
          - mutt
          - notmuch
          - getmail
          - offlineimap
          - mailcap
          - lynx
          - socat
          - python
          - python2
          - python3
          - valgrind
          - ipmitool

    - name: Personal Stuffs
      package: name={{item}} state=installed
      with_items:
          - homebank
          - keepassxc
          - inadyn
          - duplicity

    - name: IBM Packages
      package: name={{item}} state=installed
      with_items:
          - '@IBM Client Base'
          - '@IBM Licensed'
          - '@IBM Lotus Mobility Connect'
          - '@IBM Notes'
          - '@IBM Openconnect'
          - '@IBM Security Compliance'
          - '@Development Tools'
          - '@C Development Tools and Libraries'
          - ibm-ca-certificates
          - ibm-lotus-notes
          - CrashPlan
          - ecpinstall
          - ecpdelegate
